.TH leterrier-fubuki 1 "November 14, 2010"
.SH NAME
leterrier\-fubuki- a Fubuki game
.SH SYNOPSIS
.B leterrier\-fubuki
.SH DESCRIPTION
is a program which let's you playing Fubuki !
.PP

leterrier\-calculette\-capricieuse (1)
.SH AUTHOR
This manual page and the script were written by Jean-Louis FRucot
<frucot.jeanlouis@free.fr>.
