#!/bin/bash
ICON=leterrier-fubuki.desktop
ALACARTEDIR=/usr/share/abuledu-alacarte/data/profile1.applications

#alacarte
if [ -f "${ALACARTEDIR}/${ICON}" ]; then
    rm -f ${ALACARTEDIR}/${ICON}
fi

#DEBHELPER#
